#!/usr/bin/env python3
"""
Generate config.h from config.yaml or CLI. Run from project root:
  python3 configure.py
  python3 configure.py --num-mice 2 --logic-mode or
  python3 configure.py --list
"""
from pathlib import Path
import argparse
import re

CONFIG_H = Path(__file__).resolve().parent / "config.h"
CONFIG_YAML = Path(__file__).resolve().parent / "config.yaml"

LOGIC_MODES = {
    "sum": 0, "average": 1, "max": 2,
    "min": 3, "and": 4, "or": 5, "xor": 6,
    "nand": 7, "nor": 8, "xnor": 9,
}
INPUT_MODES = {"uart": 0, "quadrature": 1, "both": 2}
OUTPUT_MODES = {"combined": 0, "separate": 1}


def load_yaml(path: Path) -> dict:
    out = {}
    if not path.exists():
        return out
    try:
        import yaml
        with open(path) as f:
            out = yaml.safe_load(f) or {}
    except ImportError:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                m = re.match(r"(\w+):\s*(.+)", line)
                if m:
                    key, val = m.group(1), m.group(2).strip().split("#")[0].strip()
                    if not val:
                        continue
                    if val.isdigit():
                        out[key] = int(val)
                    else:
                        try:
                            out[key] = float(val)
                        except ValueError:
                            out[key] = val
    return out


def write_config_h(num_mice: int, logic_mode: int, input_mode: int, output_mode: int, amplify: float, quad_scale: int) -> None:
    content = f"""/* Generated by configure.py from config.yaml or CLI. Edit config.yaml and run configure.py to change. */
#ifndef CONFIG_H
#define CONFIG_H

#define NUM_MICE        {num_mice}
#define LOGIC_MODE      {logic_mode}
#define INPUT_MODE      {input_mode}
#define OUTPUT_MODE     {output_mode}
#define AMPLIFY         {float(amplify)}f
#define QUAD_SCALE      {quad_scale}

#endif
"""
    CONFIG_H.write_text(content)
    print(f"Wrote {CONFIG_H}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate config.h for amplified mouse firmware")
    ap.add_argument("--num-mice", type=int, metavar="N", help="Number of mice (2-6)")
    ap.add_argument("--logic-mode", choices=list(LOGIC_MODES), metavar="MODE", help="Logic: sum, average, max, min, and, or, xor, nand, nor, xnor")
    ap.add_argument("--input-mode", choices=list(INPUT_MODES), metavar="MODE", help="Input: uart, quadrature, both")
    ap.add_argument("--output-mode", choices=list(OUTPUT_MODES), metavar="MODE", help="Output: combined (1 mouse) or separate (6 mice)")
    ap.add_argument("--amplify", type=float, metavar="F", help="Amplification factor")
    ap.add_argument("--quad-scale", type=int, metavar="N", help="Quadrature scale")
    ap.add_argument("--list", action="store_true", help="List options and exit")
    args = ap.parse_args()

    if args.list:
        print("Logic modes:", ", ".join(LOGIC_MODES))
        print("Input modes:", ", ".join(INPUT_MODES))
        print("Output modes:", ", ".join(OUTPUT_MODES))
        print("num_mice: 2-6, amplify: float, quad_scale: int")
        return

    cfg = load_yaml(CONFIG_YAML)
    num_mice = args.num_mice if args.num_mice is not None else int(cfg.get("num_mice", 6))
    logic_mode = LOGIC_MODES[args.logic_mode] if args.logic_mode is not None else LOGIC_MODES.get(
        str(cfg.get("logic_mode", "sum")).lower(), 0
    )
    input_mode = INPUT_MODES[args.input_mode] if args.input_mode is not None else INPUT_MODES.get(
        str(cfg.get("input_mode", "uart")).lower(), 0
    )
    output_mode = OUTPUT_MODES[args.output_mode] if args.output_mode is not None else OUTPUT_MODES.get(
        str(cfg.get("output_mode", "combined")).lower(), 0
    )
    amplify = args.amplify if args.amplify is not None else float(cfg.get("amplify", 1.0))
    quad_scale = args.quad_scale if args.quad_scale is not None else int(cfg.get("quad_scale", 2))

    if num_mice < 2 or num_mice > 6:
        raise SystemExit("num_mice must be 2-6")
    if quad_scale < 1:
        quad_scale = 1

    write_config_h(num_mice, logic_mode, input_mode, output_mode, amplify, quad_scale)


if __name__ == "__main__":
    main()
