/* Generated by configure.py from config.yaml or CLI. Edit config.yaml and run configure.py to change. */
#ifndef CONFIG_H
#define CONFIG_H

#define NUM_MICE        6
#define LOGIC_MODE      0
#define INPUT_MODE      0
#define AMPLIFY         1.0f
#define QUAD_SCALE      2

#endif
