/* Generated by scripts/configure.py from config/config.yaml or CLI. Edit config/config.yaml and run scripts/configure.py to change. */
#ifndef CONFIG_H
#define CONFIG_H

#define NUM_MICE        6
#define LOGIC_MODE      0
#define INPUT_MODE      2
#define OUTPUT_MODE     1
#define AMPLIFY         1.0f
#define QUAD_SCALE      2

#endif
